export enum ROLE {
  FARMER = 'FARMER',
  ADMIN = 'ADMIN',
}

export enum POST_STATUS {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
